// Deploy a generated project by pushing it to a GitHub repo (one commit via the
// Git Trees API) and returning a one-click "Deploy to Render" link — Render reads
// the project's render.yaml Blueprint, so no Render API key is needed; the user
// finishes the deploy in their own Render dashboard. Fail-soft without a token.
import { env } from "@omni/env-config";
import { logger } from "@omni/sdk";
import type { ProjectFile } from "./e2b.js";

export function githubConfigured(): boolean {
  return !!env.GITHUB_TOKEN;
}

export interface DeployResult {
  repoUrl: string;
  renderDeployUrl: string;
  branch: string;
}

const API = "https://api.github.com";

async function gh<T>(path: string, method: string, token: string, body?: unknown): Promise<T> {
  const res = await fetch(`${API}${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "User-Agent": "OmniAppBuilder",
      ...(body ? { "content-type": "application/json" } : {}),
    },
    body: body ? JSON.stringify(body) : undefined,
    signal: AbortSignal.timeout(30_000),
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    let msg = `GitHub ${method} ${path} -> ${res.status}`;
    try {
      msg = (JSON.parse(text) as { message?: string }).message ?? msg;
    } catch {
      /* keep default */
    }
    throw new Error(msg);
  }
  return (await res.json()) as T;
}

function slug(name: string): string {
  return name.replace(/[^a-z0-9-]+/gi, "-").replace(/^-+|-+$/g, "").toLowerCase() || "omni-app";
}

/** Create a private repo in the token owner's account and push all files. */
export async function deployProject(opts: {
  name: string;
  files: ProjectFile[];
  idSuffix: string;
}): Promise<DeployResult> {
  const token = env.GITHUB_TOKEN;
  if (!token) {
    throw new Error(
      "Deploy needs a GitHub token. Add GITHUB_TOKEN (with the 'repo' scope) to ~/omni/.env and restart the API — or use Export .zip to deploy the code yourself.",
    );
  }

  const repoName = `${slug(opts.name)}-${opts.idSuffix.slice(0, 6)}`;
  const repo = await gh<{ full_name: string; html_url: string; default_branch: string; owner: { login: string } }>(
    "/user/repos",
    "POST",
    token,
    { name: repoName, private: true, auto_init: true, description: "Full-stack app generated by Omni" },
  );
  const [owner, name] = repo.full_name.split("/");
  const branch = repo.default_branch || "main";

  // auto_init made an initial commit; build a new tree on top of it.
  const ref = await gh<{ object: { sha: string } }>(
    `/repos/${owner}/${name}/git/ref/heads/${branch}`,
    "GET",
    token,
  );
  const baseCommit = await gh<{ tree: { sha: string } }>(
    `/repos/${owner}/${name}/git/commits/${ref.object.sha}`,
    "GET",
    token,
  );
  const tree = await gh<{ sha: string }>(`/repos/${owner}/${name}/git/trees`, "POST", token, {
    base_tree: baseCommit.tree.sha,
    tree: opts.files.map((f) => ({
      path: f.path.replace(/^\/+/, ""),
      mode: "100644",
      type: "blob",
      content: f.content,
    })),
  });
  const commit = await gh<{ sha: string }>(`/repos/${owner}/${name}/git/commits`, "POST", token, {
    message: "Deploy from Omni",
    tree: tree.sha,
    parents: [ref.object.sha],
  });
  await gh(`/repos/${owner}/${name}/git/refs/heads/${branch}`, "PATCH", token, { sha: commit.sha });

  logger.info({ repo: repo.full_name }, "[deploy] pushed project to GitHub");
  return {
    repoUrl: repo.html_url,
    renderDeployUrl: `https://render.com/deploy?repo=${encodeURIComponent(repo.html_url)}`,
    branch,
  };
}
